#!/usr/bin/python
# -*- coding: utf-8 -*-
import math
x = int(input("Lietoaj, ludzu ievadi skaitli: "))
print "Dalijumu atlikumu vertibas tabula".center(80)
print " \t1 \t2 \t3 \t4 \t5 \t6 \t7 \t8 \t9"
print x
k = 1
while k <= 9:
    print " %d\n"%(x % k),
    a=x % k
    k = k + 1
